#!/bin/bash

usage() {
    printf "Manipulate volume with pactl\n\n"
    printf "Usage: volume [ inc | dec | toggle | display | help ]"
}

display_volume() {
    local muted="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')"

    if [[ "$muted" == "yes" ]]; then
        echo "muted"
    else
        echo "$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | tr -d '[:space:]%')"
    fi
}

if [[ $# == 0 ]]; then
    usage
    return 1
fi

if [[ -z $(which pactl 2>/dev/null) ]]; then
    printf "Please install pactl\n"
    return 1
fi

while [[ $# > 0 ]]
do
    case "$1" in
        inc)
            pactl set-sink-volume @DEFAULT_SINK@ +2%
            ;;
        dec)
            pactl set-sink-volume @DEFAULT_SINK@ -2%
            ;;
        toggle)
            pactl set-sink-mute @DEFAULT_SINK@ $1
            ;;
        display)
            display_volume
            ;;
        help|*)
            usage
            ;;
    esac
    shift
done
